// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GyStLiwGKVtOwyHHluuRR5YCOqBsgDw',
    appId: '1:258781886380:web:b78d5d92f6f2342a886c09',
    messagingSenderId: '258781886380',
    projectId: 'hike-99ade',
    authDomain: 'hike-99ade.firebaseapp.com',
    storageBucket: 'hike-99ade.firebasestorage.app',
    measurementId: 'G-41GZ171Y7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Ec4Q2h2-95K5gE6V5ClT4e2P5c1hbMk',
    appId: '1:258781886380:android:2aa76e2c60232333886c09',
    messagingSenderId: '258781886380',
    projectId: 'hike-99ade',
    storageBucket: 'hike-99ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ2A2mu9ffL1XK9yIQrIacQPEbkL3wrr4',
    appId: '1:258781886380:ios:2385a5ba3a1c0b1e886c09',
    messagingSenderId: '258781886380',
    projectId: 'hike-99ade',
    storageBucket: 'hike-99ade.firebasestorage.app',
    iosBundleId: 'com.example.hikeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ2A2mu9ffL1XK9yIQrIacQPEbkL3wrr4',
    appId: '1:258781886380:ios:2385a5ba3a1c0b1e886c09',
    messagingSenderId: '258781886380',
    projectId: 'hike-99ade',
    storageBucket: 'hike-99ade.firebasestorage.app',
    iosBundleId: 'com.example.hikeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0GyStLiwGKVtOwyHHluuRR5YCOqBsgDw',
    appId: '1:258781886380:web:3fa80ee5450a10f8886c09',
    messagingSenderId: '258781886380',
    projectId: 'hike-99ade',
    authDomain: 'hike-99ade.firebaseapp.com',
    storageBucket: 'hike-99ade.firebasestorage.app',
    measurementId: 'G-8Q8HQNSDPK',
  );
}
